### ISSUE TITLE
[Resolvido] Renomear o sistema. 2d20 já é usado para outro sistema

### ISSUE THREAD

**Issue by roroire** [renatodex/fabulas-e-goblins#35]
Na página https://www.fabulasegoblins.com.br/docs/8-system-2d20/system-introduction é dito que esse é um sistema criado para o Fábulas & Goblins, mas um sistema com esse nome já existe, https://www.drivethrurpg.com/product/403658/2d20-System-Reference-Document, e é diferente do Fábulas & Goblins.

Problema resolvido, agora a página se chama:
https://www.fabulasegoblins.com.br/docs/8-system-duo20/system-introduction

**Comment by renatodex** [comment]
Valeu pelo Issue, esqueci de comentar e fechar!
